### ISSUE TITLE
How to access the dataset?

### ISSUE THREAD

**Issue by junzhuang-code** [nyuad-cai/CXR-ML-GZSL#4]
In "train_densenet121.sh" script, I notice that the program will read the data from "/data/shamoutlab/nih_chest_xrays". However, I didn't find such data in the box (the link of the dataset).
Would you provide more details about that? We would like to reimplement the code.

Thanks,

**Comment by nasir6** [comment]
@junzhuang-code we used the NIH chest X-ray dataset the [link](https://nihcc.app.box.com/v/ChestXray-NIHCC) to download the dataset is shared in the readme. Please download it and change the path "/data/shamoutlab/nih_chest_xrays" to yours.
