### ISSUE TITLE
precision and recall code

### ISSUE THREAD

**Issue by chinmay5** [nyuad-cai/CXR-ML-GZSL#6]
Dear @nasir6 sorry to open the issue again. I was unable to produce the numbers reported by the paper by means of the code you shared. It would be great if you could just integrate the Precision and recall code as part of the repo itself. This would allow for easy reproducibility. Thanks in advance.

**Comment by kiwi12138** [comment]
Hi chinmay5, have you figured out how to calculate the precision and recall in this project? I have tried to write by myself but the value is quite different.
